### ISSUE TITLE
Google Chrome

### ISSUE THREAD

**Issue by BaburMB** [brandcolors/feedback#451] opened 2016-04-21 17:06 UTC
- [x] _Brand Name_: Google Chrome
- [x] _Brand Colors_: 4586f3, 4586f3, 4586f3, dc493a
- [x] _Brand URL_: https://www.google.com/chrome/
- [x] _Where/how you found the brand colors_: Adobe Photoshop Color Picker
- [x] New on brandcolors.net

**Comment by dkhamsing** [comment] 2016-04-21 17:08
@BaburMB the first 3 colors are the same, can you update?

**Comment by BaburMB** [comment] 2016-04-21 17:13
done

**Comment by dkhamsing** [comment] 2016-04-21 17:17
Submitted brand `1376` for review, thanks

**Comment by galengidman** [comment] 2017-01-13 17:52
Choosing not to publish since this is basically a dupe of Google proper. Thanks for taking the time to submit though.

**Closed by galengidman** 2017-01-13 17:52 UTC
Labels: colors, pending
