### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ltsc1980** [brandcolors/feedback#465] opened 2016-05-26 03:41 UTC
- [x] *Brand Name*: Windows
- [x] *Brand Colors*: #0078d6
- [x] *Brand URL*: http://windows.com/
- [x] *Updating brand* 
- [x] *Where/how you found the brand colors*: Windows 10.

**Comment by dkhamsing** [comment] 2016-06-20 04:31
Closing, dupe of #474

**Closed by dkhamsing** 2016-06-20 04:31 UTC
Labels: colors
