### ISSUE TITLE
Wikimedia

### ISSUE THREAD

**Issue by RachelWatson9b13a9** [brandcolors/feedback#697] opened 2018-01-14 18:41 UTC
- [x] *Brand Name*:Wikimedia
- [x] *Brand Colors*:990000, 006699, 339966, 484848, 666666.
- [x] *Brand URL*:https://www.wikimedia.org/
- [x] *Where/how you found the brand colors*:https://wikimediafoundation.org/wiki/Archived/Wikimedia_visual_identity_guidelines

**Comment by RachelWatson9b13a9** [comment] 2018-01-14 19:02
https://livestream.com/internetsociety/wikidaynyc

**Comment by oxguy3** [comment] 2018-01-16 16:05
Duplicate of #666

**Closed** 2018-01-16 16:43 UTC
